CREATE TABLE IF NOT EXISTS newstags (
    News_Id bigint NULL,
    Tag_Id bigint NULL,

    CONSTRAINT FK_TAG_NEWS FOREIGN KEY (News_Id) REFERENCES news(Id) ON DELETE CASCADE,
    CONSTRAINT FK_NEWS_TAG FOREIGN KEY (Tag_Id) REFERENCES tags(Id) ON DELETE CASCADE
);